# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' 
        cache-dependency-path: eafitbike/package-lock.json
    - run: npm i
      name: Installing Node Modules
      working-directory: eafitbike/
    - run: npm run lint
      name: Running Linter
      working-directory: eafitbike/
    - run: npm run test
      name: Running Unit Tests
      working-directory: eafitbike/
    - run: npm run build
      name: Running Build
      working-directory: eafitbike/
  
  sonarqube-analysis:
    runs-on: ubuntu-latest
    steps:
    - run: npm i -g typescript
      working-directory: eafitbike/
    - uses: actions/checkout@v2
      with:
        projectBaseDir: eafitbike/src
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  
